### ISSUE TITLE
Issue: P3

### ISSUE THREAD

**Issue by we-chintan-p001** [khushal-y001/flutter_challenges#2]
- Use dart formatter to format on save. [issue with formatting](https://github.com/we-khushal-y001/flutter_challenges/blob/17e5fdc27c5ae42655535561677cbe467e75399f/organic_farm/lib/main.dart#LL12C47-L12C47)

- Could you remove code that is unnecessary? [commented code](https://github.com/we-khushal-y001/flutter_challenges/blob/17e5fdc27c5ae42655535561677cbe467e75399f/organic_farm/lib/main.dart#L9C15-L10)

- We should extract the main app and put it in a new file. [Main App](https://github.com/we-khushal-y001/flutter_challenges/blob/17e5fdc27c5ae42655535561677cbe467e75399f/organic_farm/lib/main.dart#L27-L51)

- Use dart analyzer to check if there are any warnings ["${imagePath}welcome_image.png"; Brackets not needed](https://github.com/we-khushal-y001/flutter_challenges/blob/17e5fdc27c5ae42655535561677cbe467e75399f/organic_farm/lib/constants/app_images.dart#L4)

- What purpose this file has? [file](https://github.com/we-khushal-y001/flutter_challenges/blob/17e5fdc27c5ae42655535561677cbe467e75399f/organic_farm/lib/services/service_locator/service_locator.dart)

- Maintain Uniformity [different import styles](https://github.com/we-khushal-y001/flutter_challenges/blob/17e5fdc27c5ae42655535561677cbe467e75399f/organic_farm/lib/services/routes/routes.dart#L2C30-L3)

- Use comma to properly format code [here](https://github.com/we-khushal-y001/flutter_challenges/blob/17e5fdc27c5ae42655535561677cbe467e75399f/organic_farm/lib/widgets/app_button.dart#L8) and [here](https://github.com/we-khushal-y001/flutter_challenges/blob/17e5fdc27c5ae42655535561677cbe467e75399f/organic_farm/lib/widgets/app_button.dart#L22) and In this [file](https://github.com/we-khushal-y001/flutter_challenges/blob/17e5fdc27c5ae42655535561677cbe467e75399f/organic_farm/lib/widgets/app_text_fields.dart) as well

- Use dart formatter [Style should be in next line](https://github.com/we-khushal-y001/flutter_challenges/blob/17e5fdc27c5ae42655535561677cbe467e75399f/organic_farm/lib/widgets/app_button.dart#LL15C53-L15C53)

- Is this needed? [snackbar](https://github.com/we-khushal-y001/flutter_challenges/blob/17e5fdc27c5ae42655535561677cbe467e75399f/organic_farm/lib/widgets/app_snackbar.dart)

- imports + formatting [uniformity](https://github.com/we-khushal-y001/flutter_challenges/blob/17e5fdc27c5ae42655535561677cbe467e75399f/organic_farm/lib/widgets/overlay_helper.dart)

- Review [features](https://github.com/we-khushal-y001/flutter_challenges/tree/17e5fdc27c5ae42655535561677cbe467e75399f/organic_farm/lib/features) by yourself first do the needed changes, I'll review it after.

**Comment by we-khushal-y001** [comment]
okay I will review code and will try to improve code quality

**Comment by we-chintan-p001** [comment]
Thanks!
